# Generated by Django 4.0.1 on 2022-02-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='mealselection',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
