# Generated by Django 4.0.1 on 2022-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_mealitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Object Version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealitem',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Object Version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealselection',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Object Version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionalinfo',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Object Version'),
        ),
    ]
