# Generated by Django 4.0.1 on 2022-03-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_ingredient_version_mealitem_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='calcium',
            field=models.FloatField(default=0, verbose_name='Calcium (mg)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='calories',
            field=models.FloatField(default=0, verbose_name='Calories (cal)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='carbohydrate',
            field=models.FloatField(default=0, verbose_name='Carbohydrates (g)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='cholesterol',
            field=models.FloatField(default=0, verbose_name='Cholesterol (mg)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='fiber',
            field=models.FloatField(default=0, verbose_name='Dietary Fiber (g)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='iron',
            field=models.FloatField(default=0, verbose_name='Iron (mg)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='potassium',
            field=models.FloatField(default=0, verbose_name='Potassium (mg)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='protein',
            field=models.FloatField(default=0, verbose_name='Protein (g)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='saturated_fat',
            field=models.FloatField(default=0, verbose_name='Saturated Fat (g)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='sodium',
            field=models.FloatField(default=0, verbose_name='Sodium (mg)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='sugar',
            field=models.FloatField(default=0, verbose_name='Sugar (g)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='total_fat',
            field=models.FloatField(default=0, verbose_name='Total Fat (g)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='trans_fat',
            field=models.FloatField(default=0, verbose_name='Trans Fat (g)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='vitamin_a',
            field=models.FloatField(default=0, verbose_name='Vitamin A (RE)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='vitamin_c',
            field=models.FloatField(default=0, verbose_name='Vitamin C (mg)'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='vitamin_d',
            field=models.FloatField(default=0, verbose_name='Vitamin D (IU)'),
        ),
        migrations.DeleteModel(
            name='NutritionalInfo',
        ),
    ]
