# Generated by Django 4.0.1 on 2022-03-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_mealitem_nutrition_mealitem_calcium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
