# Generated by Django 4.0.1 on 2022-03-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_passwordresettoken_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='version',
        ),
    ]
