# Generated by Django 4.0.1 on 2022-03-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_ingredient_version_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
    ]
