# Generated by Django 4.0.1 on 2022-04-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_delete_schoolprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='max_pieces',
            field=models.IntegerField(default=10, verbose_name='Max # of Pieces'),
        ),
    ]
