# Generated by Django 4.0.1 on 2022-04-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_mealitem_max_pieces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='graphic',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='meal_item_image'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='ImageQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_queue_image')),
                ('timestamp', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.mealitem')),
            ],
        ),
    ]
