# Generated by Django 4.0.1 on 2022-04-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_mealitem_graphic_mealitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagequeueentry',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.studentprofile'),
        ),
    ]
